structure_features = ['location', 'tag_is_button', 'tag_is_option', 'tag_is_cite', 'tag_is_title', 'tag_is_br',
                      'tag_is_figcaption', 'tag_is_img', 'tag_is_label', 'tag_is_noscript', 'tag_is_a', 'tag_is_b',
                      'tag_is_blockquote', 'tag_is_dd', 'tag_is_div', 'tag_is_dt', 'tag_is_em', 'tag_is_i',
                      'tag_is_ins', 'tag_is_li', 'tag_is_p', 'tag_is_pre', 'tag_is_small', 'tag_is_span',
                      'tag_is_strong', 'tag_is_sub', 'tag_is_sup', 'tag_is_td', 'tag_is_th', 'tag_is_time', 'tag_is_ul',
                      'tag_is_HYPERLINK', 'tag_is_ADDRESS', 'tag_is_INDIRECT_INFORMATION', 'tag_is_SOURCE',
                      'tag_is_FOOTER', 'tag_is_HEADING', 'tag_is_IGNORED', 'parent_tag_is_button', 'parent_tag_is_nav',
                      'parent_tag_is_select', 'parent_tag_is_address', 'parent_tag_is_article', 'parent_tag_is_footer',
                      'parent_tag_is_head', 'parent_tag_is_header', 'parent_tag_is_meta', 'parent_tag_is_br',
                      'parent_tag_is_figcaption', 'parent_tag_is_figure', 'parent_tag_is_form', 'parent_tag_is_iframe',
                      'parent_tag_is_img', 'parent_tag_is_input', 'parent_tag_is_label', 'parent_tag_is_a',
                      'parent_tag_is_blockquote', 'parent_tag_is_body', 'parent_tag_is_div', 'parent_tag_is_dl',
                      'parent_tag_is_em', 'parent_tag_is_i', 'parent_tag_is_li', 'parent_tag_is_main',
                      'parent_tag_is_ol', 'parent_tag_is_p', 'parent_tag_is_pre', 'parent_tag_is_section',
                      'parent_tag_is_small', 'parent_tag_is_span', 'parent_tag_is_strong', 'parent_tag_is_sub',
                      'parent_tag_is_sup', 'parent_tag_is_td', 'parent_tag_is_tr', 'parent_tag_is_ul',
                      'parent_tag_is_HYPERLINK', 'parent_tag_is_ADDRESS', 'parent_tag_is_INDIRECT_INFORMATION',
                      'parent_tag_is_FOOTER', 'parent_tag_is_HEADING', 'parent_tag_is_IGNORED',
                      'super_parent_tag_is_button', 'super_parent_tag_is_nav', 'super_parent_tag_is_select',
                      'super_parent_tag_is_address', 'super_parent_tag_is_article', 'super_parent_tag_is_footer',
                      'super_parent_tag_is_head', 'super_parent_tag_is_header', 'super_parent_tag_is_meta',
                      'super_parent_tag_is_br', 'super_parent_tag_is_figcaption', 'super_parent_tag_is_figure',
                      'super_parent_tag_is_form', 'super_parent_tag_is_hr', 'super_parent_tag_is_iframe',
                      'super_parent_tag_is_img', 'super_parent_tag_is_input', 'super_parent_tag_is_label',
                      'super_parent_tag_is_link', 'super_parent_tag_is_noscript', 'super_parent_tag_is_a',
                      'super_parent_tag_is_blockquote', 'super_parent_tag_is_body', 'super_parent_tag_is_div',
                      'super_parent_tag_is_dl', 'super_parent_tag_is_em', 'super_parent_tag_is_html',
                      'super_parent_tag_is_i', 'super_parent_tag_is_ins', 'super_parent_tag_is_li',
                      'super_parent_tag_is_main', 'super_parent_tag_is_ol', 'super_parent_tag_is_p',
                      'super_parent_tag_is_section', 'super_parent_tag_is_small', 'super_parent_tag_is_span',
                      'super_parent_tag_is_strong', 'super_parent_tag_is_sup', 'super_parent_tag_is_tbody',
                      'super_parent_tag_is_td', 'super_parent_tag_is_tr', 'super_parent_tag_is_ul',
                      'super_parent_tag_is_HYPERLINK', 'super_parent_tag_is_ADDRESS',
                      'super_parent_tag_is_INDIRECT_INFORMATION', 'super_parent_tag_is_FOOTER',
                      'super_parent_tag_is_HEADING', 'super_parent_tag_is_IGNORED', ]
