# Generated by Django 4.2.1 on 2023-06-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('content_basic', models.TextField(db_column='basic information')),
                ('content_ignored', models.TextField(db_column='ignored information')),
                ('content_deleted', models.TextField(db_column='deleted information')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('site_host', models.TextField(db_column='host')),
                ('site_name', models.TextField(db_column='name')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('request_datetime', models.DateTimeField(auto_now=True, db_column='datetime')),
                ('request_content_id', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.content')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('page_url', models.TextField(db_column='url')),
                ('page_site_id', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.site')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'page',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='content_page_id',
            field=models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.page'),
        ),
    ]
